/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIEstabelecimento.java
 *
 * Created on 21/05/2011, 00:25:49
 */

package ahoradorango;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniell
 */
public class GUIEstabelecimento extends javax.swing.JInternalFrame {

    /** Creates new form GUIEstabelecimento 
     * @throws Exception */
    public GUIEstabelecimento() throws Exception {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * @throws Exception 
     */
    private void initComponents() throws Exception {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LeitorEstabelecimentos leitorDeDados = new LeitorEstabelecimentos();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Estabelecimentos");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nome", "Endereco", "Tipo de Almoco"}
        ));
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();  
        for (int i = 0; i < 38; i++) {
        	modelo.addRow(new String [] {leitorDeDados.getEstabelecimento().get(i).getNome(),leitorDeDados.getEstabelecimento().get(i).getEndereco(), leitorDeDados.getEstabelecimento().get(i).getTipoDeAlmocoServido().toString()});
		}
          
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
