/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIPerfis.java
 *
 * Created on 28/05/2011, 16:53:28
 */

package ahoradorango;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniell
 */
public class GUIPerfis extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = -8871022739429548206L;
	
	private LeitorOpinioes leitor;
	
	/** Creates new form GUIPerfis 
     * @throws Exception */
    public GUIPerfis(LeitorOpinioes leitor) throws Exception {
    	this.leitor = leitor;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * @throws Exception 
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws Exception {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Perfis");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Indicacao de data e hora", "Nome", "Estabelecimento", "Opiniao"
            }
        ));
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setDataVector(leitor.getTableOpinioes(), new String [] {
            "Indicacao de data e hora", "Nome", "Estabelecimento", "Opiniao"
        });
        
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
