/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sobre.java
 *
 * Created on 16/05/2011, 22:33:57
 */

package ahoradorango;

import java.awt.Dimension;

/**
 *
 * @author Daniell
 */
public class Sobre extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Sobre */
    public Sobre() {
        initComponents();
    }

    public void setPosicao(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width)/2,
        (d.height - this.getSize().height)/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        TituloPrograma = new javax.swing.JLabel();
        labelGrupo = new javax.swing.JLabel();
        labelArmstrong = new javax.swing.JLabel();
        labelMatriculaArmstrong = new javax.swing.JLabel();
        labelDaniell = new javax.swing.JLabel();
        labelMatriculaDaniell = new javax.swing.JLabel();
        labelCinthia = new javax.swing.JLabel();
        labelMatriculaCinthia = new javax.swing.JLabel();

        setClosable(true);
        setTitle("A hora do Rango");

        TituloPrograma.setText("O Pitaqueiro das 12Hs");

        labelGrupo.setText("Grupo:");

        labelArmstrong.setText("Armstrong Mardilson");

        labelMatriculaArmstrong.setText("Matricula: 21011057");

        labelDaniell.setText("Daniell Wagner Azevedo de Lima");

        labelMatriculaDaniell.setText("Matricula: 21011047");

        labelCinthia.setText("Cinthia Sany ");

        labelMatriculaCinthia.setText("Matricula:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(TituloPrograma))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGrupo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDaniell)
                                .addGap(39, 39, 39)
                                .addComponent(labelMatriculaDaniell))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelArmstrong)
                                    .addComponent(labelCinthia))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMatriculaCinthia)
                                    .addComponent(labelMatriculaArmstrong))))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TituloPrograma)
                .addGap(28, 28, 28)
                .addComponent(labelGrupo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArmstrong)
                    .addComponent(labelMatriculaArmstrong))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDaniell)
                    .addComponent(labelMatriculaDaniell))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCinthia)
                    .addComponent(labelMatriculaCinthia))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloPrograma;
    private javax.swing.JLabel labelArmstrong;
    private javax.swing.JLabel labelCinthia;
    private javax.swing.JLabel labelDaniell;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelMatriculaArmstrong;
    private javax.swing.JLabel labelMatriculaCinthia;
    private javax.swing.JLabel labelMatriculaDaniell;
    // End of variables declaration//GEN-END:variables

}
