/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sobre.java
 *
 * Created on 16/05/2011, 22:33:57
 */

package ahoradorango;

import java.awt.Dimension;

/**
 *
 * @author Daniell
 */
public class Sobre extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = -5605574939332911392L;
	
	/** Creates new form Sobre */
    public Sobre() {
        initComponents();
    }

    public void setPosicao(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width)/2,
        (d.height - this.getSize().height)/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloPrograma = new javax.swing.JLabel();
        labelGrupo = new javax.swing.JLabel();
        labelArmstrong = new javax.swing.JLabel();
        labelMatriculaArmstrong = new javax.swing.JLabel();
        labelDaniell = new javax.swing.JLabel();
        labelMatriculaDaniell = new javax.swing.JLabel();
        labelCinthia = new javax.swing.JLabel();
        labelMatriculaCinthia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("A Hora Do Rango");

        TituloPrograma.setText("A Hora Do Rango");

        labelGrupo.setText("Grupo:");

        labelArmstrong.setText("Armstrong Mardilson");

        labelMatriculaArmstrong.setText("Matricula: 21011057");

        labelDaniell.setText("Daniell Wagner Azevedo de Lima");

        labelMatriculaDaniell.setText("Matricula: 21011047");

        labelCinthia.setText("Cinthia Sany ");

        labelMatriculaCinthia.setText("Matricula:");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Daniell\\Meus documentos\\NetBeansProjects\\OPitaqueiroDas12Hs\\ahoradorango.png")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGrupo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelArmstrong)
                                .addGap(18, 18, 18)
                                .addComponent(labelMatriculaArmstrong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDaniell)
                                .addGap(15, 15, 15)
                                .addComponent(labelMatriculaDaniell))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCinthia)
                                .addGap(16, 16, 16)
                                .addComponent(labelMatriculaCinthia))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(TituloPrograma)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TituloPrograma)
                .addGap(28, 28, 28)
                .addComponent(labelGrupo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArmstrong)
                    .addComponent(labelMatriculaArmstrong))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDaniell)
                    .addComponent(labelMatriculaDaniell))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCinthia)
                    .addComponent(labelMatriculaCinthia))
                .addContainerGap(344, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloPrograma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelArmstrong;
    private javax.swing.JLabel labelCinthia;
    private javax.swing.JLabel labelDaniell;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelMatriculaArmstrong;
    private javax.swing.JLabel labelMatriculaCinthia;
    private javax.swing.JLabel labelMatriculaDaniell;
    // End of variables declaration//GEN-END:variables

}
