/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 16/05/2011, 10:59:53
 */

package ahoradorango;

import java.io.File;
import java.util.GregorianCalendar;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;





/**
 *
 * @author Daniell
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Sobre GUISobre;
    private LeitorEstabelecimentos leitorEstabelecimentos;
    private LeitorOpinioes leitorOpinioes;
	private GregorianCalendar cal;
	
	public LeitorEstabelecimentos getLeitorEstabelecimentos() {
		return leitorEstabelecimentos;
	}

	public void setLeitorEstabelecimentos(LeitorEstabelecimentos leitorEstabelecimentos) {
		this.leitorEstabelecimentos = leitorEstabelecimentos;
	}


    /** Creates new form TelaPrincipal */
    public TelaPrincipal(GregorianCalendar cal) {
        initComponents();
        this.cal = cal;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuCarregar = new javax.swing.JMenu();
        itemDeMenuEstabelecimentos = new javax.swing.JMenuItem();
        itemDeMenuOpinioes = new javax.swing.JMenuItem();
        itemDeMenuPerfis = new javax.swing.JMenuItem();
        itemDeMenuSair = new javax.swing.JMenuItem();
        menuInserir = new javax.swing.JMenu();
        itemDeMenuUsuario = new javax.swing.JMenuItem();
        GerarRecomendacao = new javax.swing.JMenu();
        UsuarioCadastrado = new javax.swing.JMenuItem();
        UsuarioNaoCadastrado = new javax.swing.JMenuItem();
        menuEstabelecimento = new javax.swing.JMenu();
        ListaPorPopularidade = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        itemDeMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A Hora do Rango");

        desktop.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/ahoradorango.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        jLabel1.setBounds(260, 80, 740, 500);
        desktop.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        menuCarregar.setMnemonic('C');
        menuCarregar.setText("Carregar");

        itemDeMenuEstabelecimentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuEstabelecimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/open.jpg"))); // NOI18N
        itemDeMenuEstabelecimentos.setMnemonic('E');
        itemDeMenuEstabelecimentos.setText("Estabelecimentos");
        itemDeMenuEstabelecimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuEstabelecimentosActionPerformed(evt);
            }
        });
        menuCarregar.add(itemDeMenuEstabelecimentos);

        itemDeMenuOpinioes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuOpinioes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/open.jpg"))); // NOI18N
        itemDeMenuOpinioes.setMnemonic('O');
        itemDeMenuOpinioes.setText("Opinioes");
        itemDeMenuOpinioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuOpinioesActionPerformed(evt);
            }
        });
        menuCarregar.add(itemDeMenuOpinioes);

        itemDeMenuPerfis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuPerfis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/perfil.png"))); // NOI18N
        itemDeMenuPerfis.setMnemonic('P');
        itemDeMenuPerfis.setText("Perfis");
        itemDeMenuPerfis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					itemDeMenuPerfisActionPerformed(evt, leitorOpinioes);
				} catch (Exception e) {
					e.printStackTrace();
				}
            }
        });
        menuCarregar.add(itemDeMenuPerfis);

        itemDeMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/sair.gif"))); // NOI18N
        itemDeMenuSair.setMnemonic('r');
        itemDeMenuSair.setText("Sair");
        itemDeMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSairActionPerformed(evt);
            }
        });
        menuCarregar.add(itemDeMenuSair);

        menuBar.add(menuCarregar);

        menuInserir.setMnemonic('a');
        menuInserir.setText("Cadastrar");

        itemDeMenuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/usuario.png"))); // NOI18N
        itemDeMenuUsuario.setMnemonic('U');
        itemDeMenuUsuario.setText("Usuario");
        itemDeMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuUsuarioActionPerformed(evt);
            }
        });
        menuInserir.add(itemDeMenuUsuario);

        menuBar.add(menuInserir);

        GerarRecomendacao.setMnemonic('G');
        GerarRecomendacao.setText("Gerar Recomendacao");

        UsuarioCadastrado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        UsuarioCadastrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/usuario_cadastrado.png"))); // NOI18N
        UsuarioCadastrado.setMnemonic('s');
        UsuarioCadastrado.setText("Usuario Cadastrado");
        UsuarioCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioCadastradoActionPerformed(evt);
            }
        });
        GerarRecomendacao.add(UsuarioCadastrado);

        UsuarioNaoCadastrado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        UsuarioNaoCadastrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/usua_nao_cadastrado.gif"))); // NOI18N
        UsuarioNaoCadastrado.setMnemonic('a');
        UsuarioNaoCadastrado.setText("Usuario não Cadastrado");
        UsuarioNaoCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioNaoCadastradoActionPerformed(evt);
            }
        });
        GerarRecomendacao.add(UsuarioNaoCadastrado);

        menuBar.add(GerarRecomendacao);

        menuEstabelecimento.setMnemonic('e');
        menuEstabelecimento.setText("Estabelecimento");

        ListaPorPopularidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        ListaPorPopularidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/lista_popularidade.gif"))); // NOI18N
        ListaPorPopularidade.setMnemonic('l');
        ListaPorPopularidade.setText("Listar por Popularidade");
        ListaPorPopularidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaPorPopularidadeActionPerformed(evt);
            }
        });
        menuEstabelecimento.add(ListaPorPopularidade);

        menuBar.add(menuEstabelecimento);

        menuAjuda.setMnemonic('A');
        menuAjuda.setText("Ajuda");

        contentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/ajuda.jpg"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Conteudo");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        menuAjuda.add(contentMenuItem);

        itemDeMenuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/sobre.jpg"))); // NOI18N
        itemDeMenuSobre.setMnemonic('b');
        itemDeMenuSobre.setText("Sobre");
        itemDeMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemDeMenuSobre);

        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Acoes dos items de Menu
     */
    
    private void itemDeMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemDeMenuSairActionPerformed

    private void itemDeMenuEstabelecimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuEstabelecimentosActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FiltroCSV());
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            
            File file = fileChooser.getSelectedFile();
            try {
            	leitorEstabelecimentos = new LeitorEstabelecimentos(file);

            
            
            } catch (Exception ex) {
            	JOptionPane.showMessageDialog(this, "Houve um prolema ao acessar o arquivo" + file.getAbsolutePath(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
        	JOptionPane.showMessageDialog(this, "Voce ainda nao abriu o arquivo", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_itemDeMenuEstabelecimentosActionPerformed

    private void itemDeMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSobreActionPerformed
        if ((GUISobre == null) || (!GUISobre.isVisible())) {
            GUISobre = new Sobre();
            desktop.add(GUISobre);
            GUISobre.setPosicao();
            GUISobre.setVisible(true);
        }
    }//GEN-LAST:event_itemDeMenuSobreActionPerformed

    private void UsuarioCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioCadastradoActionPerformed
        GUIUsuarioCadastrado usucadas = new GUIUsuarioCadastrado(leitorOpinioes);
        desktop.add(usucadas);
        usucadas.setVisible(true);
    }//GEN-LAST:event_UsuarioCadastradoActionPerformed

    private void itemDeMenuOpinioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuOpinioesActionPerformed
         JFileChooser fileChooser = new JFileChooser();
         fileChooser.addChoosableFileFilter(new FiltroDATA());
         int returnVal = fileChooser.showOpenDialog(this);
         if (returnVal == JFileChooser.APPROVE_OPTION) {
     	 	File file = fileChooser.getSelectedFile();
     	 	leitorOpinioes = new LeitorOpinioes(file, leitorEstabelecimentos);
     	 	try {
     	 		leitorOpinioes.leLinhas();
     	 	} catch (Exception ex) {
     	 		JOptionPane.showMessageDialog(this, "Houve um prolema ao acessar o arquivo" + file.getAbsolutePath(), "Erro", JOptionPane.ERROR_MESSAGE);
     	 	}
          } else {
         	 JOptionPane.showMessageDialog(this, "Voce ainda nao abriu o arquivo", "Erro", JOptionPane.ERROR_MESSAGE);
          }

    }//GEN-LAST:event_itemDeMenuOpinioesActionPerformed

    private void itemDeMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuUsuarioActionPerformed
       GUICadastrarUsuario GUIUsuario = new GUICadastrarUsuario(leitorOpinioes, cal);
       desktop.add(GUIUsuario);
       GUIUsuario.setVisible(true);
    }//GEN-LAST:event_itemDeMenuUsuarioActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        GUIAjuda guiAjuda = new GUIAjuda();
        desktop.add(guiAjuda);
        guiAjuda.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void itemDeMenuPerfisActionPerformed(java.awt.event.ActionEvent evt, LeitorOpinioes leitorOpinioes) throws Exception {//GEN-FIRST:event_itemDeMenuPerfisActionPerformed
        GUIPerfis guiPerfis = new GUIPerfis(leitorOpinioes);
        desktop.add(guiPerfis);
        guiPerfis.setVisible(true);
        AlgoritmoDeRecomendacaoPopularidadeGlobal algoritmo = new AlgoritmoDeRecomendacaoPopularidadeGlobal();
        algoritmo.determinaPopularidades(leitorOpinioes);
        algoritmo.iteraPopularidades();
    }//GEN-LAST:event_itemDeMenuPerfisActionPerformed

    private void UsuarioNaoCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioNaoCadastradoActionPerformed
        GuiUsuarioNaoCadastrado guiUsuarioNaoCadastrado = new GuiUsuarioNaoCadastrado(leitorEstabelecimentos);
        desktop.add(guiUsuarioNaoCadastrado);
        guiUsuarioNaoCadastrado.setVisible(true);
    }//GEN-LAST:event_UsuarioNaoCadastradoActionPerformed

    private void ListaPorPopularidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaPorPopularidadeActionPerformed
        GUIEstabelecimentoPopularidade guiEstabelecimentoPopularidade = new GUIEstabelecimentoPopularidade();
        desktop.add(guiEstabelecimentoPopularidade);
        guiEstabelecimentoPopularidade.setVisible(true);
    }//GEN-LAST:event_ListaPorPopularidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GerarRecomendacao;
    private javax.swing.JMenuItem ListaPorPopularidade;
    private javax.swing.JMenuItem UsuarioCadastrado;
    private javax.swing.JMenuItem UsuarioNaoCadastrado;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem itemDeMenuEstabelecimentos;
    private javax.swing.JMenuItem itemDeMenuOpinioes;
    private javax.swing.JMenuItem itemDeMenuPerfis;
    private javax.swing.JMenuItem itemDeMenuSair;
    private javax.swing.JMenuItem itemDeMenuSobre;
    private javax.swing.JMenuItem itemDeMenuUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCarregar;
    private javax.swing.JMenu menuEstabelecimento;
    private javax.swing.JMenu menuInserir;
    // End of variables declaration//GEN-END:variables
    
    
}
