/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 16/05/2011, 10:59:53
 */

package ahoradorango;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author Daniell
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Sobre GUISobre;
    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuCarregar = new javax.swing.JMenu();
        itemDeMenuEstabelecimentos = new javax.swing.JMenuItem();
        itemDeMenuOpinioes = new javax.swing.JMenuItem();
        itemDeMenuSair = new javax.swing.JMenuItem();
        menuInserir = new javax.swing.JMenu();
        itemDeMenuUsuario = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        GerarRecomendacao = new javax.swing.JMenu();
        UsuarioCadastrado = new javax.swing.JMenuItem();
        UsuarioNaoCadastrado = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        itemDeMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O Pitaqueiro das 12 HS");

        desktop.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\workspace\\AHoraDoRango\\ahoradorango.png")); 
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        jLabel1.setBounds(260, 80, 740, 500);
        desktop.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        menuCarregar.setMnemonic('C');
        menuCarregar.setText("Carregar");

        itemDeMenuEstabelecimentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuEstabelecimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/open.jpg"))); // NOI18N
        itemDeMenuEstabelecimentos.setMnemonic('E');
        itemDeMenuEstabelecimentos.setText("Estabelecimentos");
        itemDeMenuEstabelecimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuEstabelecimentosActionPerformed(evt);
            }
        });
        menuCarregar.add(itemDeMenuEstabelecimentos);

        itemDeMenuOpinioes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuOpinioes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/open.jpg"))); // NOI18N
        itemDeMenuOpinioes.setMnemonic('O');
        itemDeMenuOpinioes.setText("Opinioes");
        itemDeMenuOpinioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuOpinioesActionPerformed(evt);
            }
        });
        menuCarregar.add(itemDeMenuOpinioes);

        itemDeMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/sair.gif"))); // NOI18N
        itemDeMenuSair.setMnemonic('S');
        itemDeMenuSair.setText("Sair");
        itemDeMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSairActionPerformed(evt);
            }
        });
        menuCarregar.add(itemDeMenuSair);

        menuBar.add(menuCarregar);

        menuInserir.setMnemonic('I');
        menuInserir.setText("Inserir");

        itemDeMenuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoradorango/usuario.png"))); // NOI18N
        itemDeMenuUsuario.setMnemonic('U');
        itemDeMenuUsuario.setText("Usuario");
        itemDeMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuUsuarioActionPerformed(evt);
            }
        });
        menuInserir.add(itemDeMenuUsuario);

        copyMenuItem.setText("Copy");
        menuInserir.add(copyMenuItem);

        pasteMenuItem.setText("Paste");
        menuInserir.add(pasteMenuItem);

        deleteMenuItem.setText("Delete");
        menuInserir.add(deleteMenuItem);

        menuBar.add(menuInserir);

        GerarRecomendacao.setMnemonic('G');
        GerarRecomendacao.setText("Gerar Recomendacao");

        UsuarioCadastrado.setText("Usuario Cadastrado");
        UsuarioCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioCadastradoActionPerformed(evt);
            }
        });
        GerarRecomendacao.add(UsuarioCadastrado);

        UsuarioNaoCadastrado.setText("Usuario não Cadastrado");
        GerarRecomendacao.add(UsuarioNaoCadastrado);

        menuBar.add(GerarRecomendacao);

        menuAjuda.setMnemonic('A');
        menuAjuda.setText("Ajuda");

        contentMenuItem.setText("Contents");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        menuAjuda.add(contentMenuItem);

        itemDeMenuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        itemDeMenuSobre.setMnemonic('O');
        itemDeMenuSobre.setText("Sobre");
        itemDeMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemDeMenuSobre);

        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Acoes dos items de Menu
     */
    
    private void itemDeMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemDeMenuSairActionPerformed

    private void itemDeMenuEstabelecimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuEstabelecimentosActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            GUIEstabelecimento guiEstabelecimentos = new GUIEstabelecimento();
            File file = fileChooser.getSelectedFile();
            try {
              // What to do with the file, e.g. display it in a TextArea
            //tabelaEstabelecimentos.read( new FileReader( file.getAbsolutePath() ), null );
            desktop.add(guiEstabelecimentos);
            guiEstabelecimentos.setVisible(true);
            
            
            } catch (Exception ex) {
              System.out.println("problem accessing file"+file.getAbsolutePath());
            }
            
        } else {
            System.out.println("File access cancelled by user.");
        }

    }//GEN-LAST:event_itemDeMenuEstabelecimentosActionPerformed

    private void itemDeMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSobreActionPerformed
        if ((GUISobre == null) || (!GUISobre.isVisible())) {
            GUISobre = new Sobre();
            desktop.add(GUISobre);
            GUISobre.setPosicao();
            GUISobre.setVisible(true);
        }
    }//GEN-LAST:event_itemDeMenuSobreActionPerformed

    private void UsuarioCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioCadastradoActionPerformed
        UsuarioCadastrado usucadas = new UsuarioCadastrado();
        desktop.add(usucadas);
        usucadas.setVisible(true);
    }//GEN-LAST:event_UsuarioCadastradoActionPerformed

    private void itemDeMenuOpinioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuOpinioesActionPerformed
         JFileChooser fileChooser = new JFileChooser();
         int returnVal = fileChooser.showOpenDialog(this);
    }//GEN-LAST:event_itemDeMenuOpinioesActionPerformed

    private void itemDeMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuUsuarioActionPerformed
       GUIUsuario GUIUsuario = new GUIUsuario();
       desktop.add(GUIUsuario);
       GUIUsuario.setVisible(true);
    }//GEN-LAST:event_itemDeMenuUsuarioActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        GUIEstabelecimento guiEstabelecimento = new GUIEstabelecimento();
        desktop.add(guiEstabelecimento);
        guiEstabelecimento.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GerarRecomendacao;
    private javax.swing.JMenuItem UsuarioCadastrado;
    private javax.swing.JMenuItem UsuarioNaoCadastrado;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem itemDeMenuEstabelecimentos;
    private javax.swing.JMenuItem itemDeMenuOpinioes;
    private javax.swing.JMenuItem itemDeMenuSair;
    private javax.swing.JMenuItem itemDeMenuSobre;
    private javax.swing.JMenuItem itemDeMenuUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCarregar;
    private javax.swing.JMenu menuInserir;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables
    
    
}
